export interface CommandEntry {
  label: string;
  syntax: string;
  info: string;
  sample?: string;
}

export interface CommandGroup {
  title: string;
  accent: string;
  entries: CommandEntry[];
}

export const COMMAND_GROUPS: CommandGroup[] = [
  {
    title: 'Fractions & Roots',
    accent: '#6366f1',
    entries: [
      { label: String.raw`\frac`, syntax: '{a}{b}', info: 'Fraction', sample: String.raw`\frac{a}{b}` },
      { label: String.raw`\dfrac`, syntax: '{a}{b}', info: 'Display-style fraction (larger)', sample: String.raw`\dfrac{a}{b}` },
      { label: String.raw`\tfrac`, syntax: '{a}{b}', info: 'Text-style fraction (smaller)', sample: String.raw`\tfrac{a}{b}` },
      { label: String.raw`\sqrt`, syntax: '[n]{x}', info: 'Square or nth root', sample: String.raw`\sqrt{x}` },
      { label: String.raw`\binom`, syntax: '{n}{k}', info: 'Binomial coefficient', sample: String.raw`\binom{n}{k}` },
    ],
  },
  {
    title: 'Big Operators',
    accent: '#059669',
    entries: [
      { label: String.raw`\sum`, syntax: '_{i}^{n}', info: 'Summation', sample: String.raw`\sum_{i=1}^{n}` },
      { label: String.raw`\prod`, syntax: '_{i}^{n}', info: 'Product', sample: String.raw`\prod_{i=1}^{n}` },
      { label: String.raw`\int`, syntax: '_{a}^{b}', info: 'Integral', sample: String.raw`\int_{a}^{b}` },
      { label: String.raw`\iint`, syntax: '', info: 'Double integral', sample: String.raw`\iint` },
      { label: String.raw`\iiint`, syntax: '', info: 'Triple integral', sample: String.raw`\iiint` },
      { label: String.raw`\oint`, syntax: '', info: 'Contour integral', sample: String.raw`\oint` },
      { label: String.raw`\lim`, syntax: String.raw`_{x\to a}`, info: 'Limit', sample: String.raw`\lim_{x\to 0}` },
      { label: String.raw`\inf`, syntax: '', info: 'Infimum', sample: String.raw`\inf` },
      { label: String.raw`\sup`, syntax: '', info: 'Supremum', sample: String.raw`\sup` },
      { label: String.raw`\max`, syntax: '', info: 'Maximum', sample: String.raw`\max` },
      { label: String.raw`\min`, syntax: '', info: 'Minimum', sample: String.raw`\min` },
    ],
  },
  {
    title: 'Functions',
    accent: '#0891b2',
    entries: [
      { label: String.raw`\log`, syntax: '', info: 'Logarithm', sample: String.raw`\log x` },
      { label: String.raw`\ln`, syntax: '', info: 'Natural logarithm', sample: String.raw`\ln x` },
      { label: String.raw`\exp`, syntax: '', info: 'Exponential', sample: String.raw`\exp(x)` },
      { label: String.raw`\sin`, syntax: '', info: 'Sine', sample: String.raw`\sin\theta` },
      { label: String.raw`\cos`, syntax: '', info: 'Cosine', sample: String.raw`\cos\theta` },
      { label: String.raw`\tan`, syntax: '', info: 'Tangent', sample: String.raw`\tan\theta` },
      { label: String.raw`\arcsin`, syntax: '', info: 'Arcsine', sample: String.raw`\arcsin x` },
      { label: String.raw`\arccos`, syntax: '', info: 'Arccosine', sample: String.raw`\arccos x` },
      { label: String.raw`\arctan`, syntax: '', info: 'Arctangent', sample: String.raw`\arctan x` },
      { label: String.raw`\sinh`, syntax: '', info: 'Hyperbolic sine', sample: String.raw`\sinh x` },
      { label: String.raw`\cosh`, syntax: '', info: 'Hyperbolic cosine', sample: String.raw`\cosh x` },
      { label: String.raw`\tanh`, syntax: '', info: 'Hyperbolic tangent', sample: String.raw`\tanh x` },
      { label: String.raw`\det`, syntax: '', info: 'Determinant', sample: String.raw`\det A` },
      { label: String.raw`\dim`, syntax: '', info: 'Dimension', sample: String.raw`\dim V` },
      { label: String.raw`\ker`, syntax: '', info: 'Kernel', sample: String.raw`\ker T` },
      { label: String.raw`\gcd`, syntax: '', info: 'Greatest common divisor', sample: String.raw`\gcd(a,b)` },
    ],
  },
  {
    title: 'Relations',
    accent: '#d97706',
    entries: [
      { label: String.raw`\leq`, syntax: '', info: 'Less than or equal ≤', sample: String.raw`a \leq b` },
      { label: String.raw`\geq`, syntax: '', info: 'Greater than or equal ≥', sample: String.raw`a \geq b` },
      { label: String.raw`\neq`, syntax: '', info: 'Not equal ≠', sample: String.raw`a \neq b` },
      { label: String.raw`\approx`, syntax: '', info: 'Approximately equal ≈', sample: String.raw`a \approx b` },
      { label: String.raw`\equiv`, syntax: '', info: 'Equivalent ≡', sample: String.raw`a \equiv b` },
      { label: String.raw`\sim`, syntax: '', info: 'Similar ∼', sample: String.raw`a \sim b` },
      { label: String.raw`\simeq`, syntax: '', info: 'Similar or equal ≃', sample: String.raw`a \simeq b` },
      { label: String.raw`\cong`, syntax: '', info: 'Congruent ≅', sample: String.raw`a \cong b` },
      { label: String.raw`\propto`, syntax: '', info: 'Proportional to ∝', sample: String.raw`a \propto b` },
      { label: String.raw`\in`, syntax: '', info: 'Element of ∈', sample: String.raw`x \in A` },
      { label: String.raw`\notin`, syntax: '', info: 'Not element of ∉', sample: String.raw`x \notin A` },
      { label: String.raw`\subset`, syntax: '', info: 'Subset ⊂', sample: String.raw`A \subset B` },
      { label: String.raw`\subseteq`, syntax: '', info: 'Subset or equal ⊆', sample: String.raw`A \subseteq B` },
      { label: String.raw`\supset`, syntax: '', info: 'Superset ⊃', sample: String.raw`A \supset B` },
      { label: String.raw`\supseteq`, syntax: '', info: 'Superset or equal ⊇', sample: String.raw`A \supseteq B` },
      { label: String.raw`\ll`, syntax: '', info: 'Much less than ≪', sample: String.raw`a \ll b` },
      { label: String.raw`\gg`, syntax: '', info: 'Much greater than ≫', sample: String.raw`a \gg b` },
    ],
  },
  {
    title: 'Arrows',
    accent: '#4f46e5',
    entries: [
      { label: String.raw`\to`, syntax: '', info: 'Right arrow →', sample: String.raw`A \to B` },
      { label: String.raw`\leftarrow`, syntax: '', info: 'Left arrow ←', sample: String.raw`A \leftarrow B` },
      { label: String.raw`\rightarrow`, syntax: '', info: 'Right arrow →', sample: String.raw`A \rightarrow B` },
      { label: String.raw`\leftrightarrow`, syntax: '', info: 'Both arrows ↔', sample: String.raw`A \leftrightarrow B` },
      { label: String.raw`\Leftarrow`, syntax: '', info: 'Double left arrow ⇐', sample: String.raw`A \Leftarrow B` },
      { label: String.raw`\Rightarrow`, syntax: '', info: 'Double right arrow ⇒', sample: String.raw`A \Rightarrow B` },
      { label: String.raw`\Leftrightarrow`, syntax: '', info: 'Double both arrows ⇔', sample: String.raw`A \Leftrightarrow B` },
      { label: String.raw`\iff`, syntax: '', info: 'If and only if ⟺', sample: String.raw`P \iff Q` },
      { label: String.raw`\implies`, syntax: '', info: 'Implies ⟹', sample: String.raw`P \implies Q` },
      { label: String.raw`\mapsto`, syntax: '', info: 'Maps to ↦', sample: String.raw`x \mapsto x^2` },
      { label: String.raw`\hookrightarrow`, syntax: '', info: 'Injection ↪', sample: String.raw`A \hookrightarrow B` },
      { label: String.raw`\twoheadrightarrow`, syntax: '', info: 'Surjection ↠', sample: String.raw`A \twoheadrightarrow B` },
      { label: String.raw`\xrightarrow`, syntax: '{label}', info: 'Labeled arrow', sample: String.raw`A \xrightarrow{\phi} B` },
    ],
  },
  {
    title: 'Greek — Lowercase',
    accent: '#7c3aed',
    entries: [
      { label: String.raw`\alpha`, syntax: '', info: 'α', sample: String.raw`\alpha` },
      { label: String.raw`\beta`, syntax: '', info: 'β', sample: String.raw`\beta` },
      { label: String.raw`\gamma`, syntax: '', info: 'γ', sample: String.raw`\gamma` },
      { label: String.raw`\delta`, syntax: '', info: 'δ', sample: String.raw`\delta` },
      { label: String.raw`\epsilon`, syntax: '', info: 'ε', sample: String.raw`\epsilon` },
      { label: String.raw`\varepsilon`, syntax: '', info: 'ε (variant)', sample: String.raw`\varepsilon` },
      { label: String.raw`\zeta`, syntax: '', info: 'ζ', sample: String.raw`\zeta` },
      { label: String.raw`\eta`, syntax: '', info: 'η', sample: String.raw`\eta` },
      { label: String.raw`\theta`, syntax: '', info: 'θ', sample: String.raw`\theta` },
      { label: String.raw`\vartheta`, syntax: '', info: 'ϑ (variant)', sample: String.raw`\vartheta` },
      { label: String.raw`\iota`, syntax: '', info: 'ι', sample: String.raw`\iota` },
      { label: String.raw`\kappa`, syntax: '', info: 'κ', sample: String.raw`\kappa` },
      { label: String.raw`\lambda`, syntax: '', info: 'λ', sample: String.raw`\lambda` },
      { label: String.raw`\mu`, syntax: '', info: 'μ', sample: String.raw`\mu` },
      { label: String.raw`\nu`, syntax: '', info: 'ν', sample: String.raw`\nu` },
      { label: String.raw`\xi`, syntax: '', info: 'ξ', sample: String.raw`\xi` },
      { label: String.raw`\pi`, syntax: '', info: 'π', sample: String.raw`\pi` },
      { label: String.raw`\varpi`, syntax: '', info: 'ϖ (variant)', sample: String.raw`\varpi` },
      { label: String.raw`\rho`, syntax: '', info: 'ρ', sample: String.raw`\rho` },
      { label: String.raw`\sigma`, syntax: '', info: 'σ', sample: String.raw`\sigma` },
      { label: String.raw`\tau`, syntax: '', info: 'τ', sample: String.raw`\tau` },
      { label: String.raw`\upsilon`, syntax: '', info: 'υ', sample: String.raw`\upsilon` },
      { label: String.raw`\phi`, syntax: '', info: 'φ', sample: String.raw`\phi` },
      { label: String.raw`\varphi`, syntax: '', info: 'φ (variant)', sample: String.raw`\varphi` },
      { label: String.raw`\chi`, syntax: '', info: 'χ', sample: String.raw`\chi` },
      { label: String.raw`\psi`, syntax: '', info: 'ψ', sample: String.raw`\psi` },
      { label: String.raw`\omega`, syntax: '', info: 'ω', sample: String.raw`\omega` },
    ],
  },
  {
    title: 'Greek — Uppercase',
    accent: '#9333ea',
    entries: [
      { label: String.raw`\Gamma`, syntax: '', info: 'Γ', sample: String.raw`\Gamma` },
      { label: String.raw`\Delta`, syntax: '', info: 'Δ', sample: String.raw`\Delta` },
      { label: String.raw`\Theta`, syntax: '', info: 'Θ', sample: String.raw`\Theta` },
      { label: String.raw`\Lambda`, syntax: '', info: 'Λ', sample: String.raw`\Lambda` },
      { label: String.raw`\Xi`, syntax: '', info: 'Ξ', sample: String.raw`\Xi` },
      { label: String.raw`\Pi`, syntax: '', info: 'Π', sample: String.raw`\Pi` },
      { label: String.raw`\Sigma`, syntax: '', info: 'Σ', sample: String.raw`\Sigma` },
      { label: String.raw`\Upsilon`, syntax: '', info: 'Υ', sample: String.raw`\Upsilon` },
      { label: String.raw`\Phi`, syntax: '', info: 'Φ', sample: String.raw`\Phi` },
      { label: String.raw`\Psi`, syntax: '', info: 'Ψ', sample: String.raw`\Psi` },
      { label: String.raw`\Omega`, syntax: '', info: 'Ω', sample: String.raw`\Omega` },
    ],
  },
  {
    title: 'Fonts & Text',
    accent: '#db2777',
    entries: [
      { label: String.raw`\text`, syntax: '{text}', info: 'Normal text in math mode', sample: String.raw`\text{hello}` },
      { label: String.raw`\mathrm`, syntax: '{text}', info: 'Roman (upright) math font', sample: String.raw`\mathrm{AB}` },
      { label: String.raw`\mathbf`, syntax: '{text}', info: 'Bold math font', sample: String.raw`\mathbf{v}` },
      { label: String.raw`\mathit`, syntax: '{text}', info: 'Italic math font', sample: String.raw`\mathit{f}` },
      { label: String.raw`\mathbb`, syntax: '{letter}', info: 'Blackboard bold ℝ ℤ ℕ', sample: String.raw`\mathbb{R}` },
      { label: String.raw`\mathcal`, syntax: '{letter}', info: 'Calligraphic font', sample: String.raw`\mathcal{L}` },
      { label: String.raw`\mathfrak`, syntax: '{letter}', info: 'Fraktur font', sample: String.raw`\mathfrak{g}` },
      { label: String.raw`\boldsymbol`, syntax: '{expr}', info: 'Bold symbol', sample: String.raw`\boldsymbol{\alpha}` },
    ],
  },
  {
    title: 'Accents & Decorators',
    accent: '#e11d48',
    entries: [
      { label: String.raw`\hat`, syntax: '{x}', info: 'Hat accent x̂', sample: String.raw`\hat{x}` },
      { label: String.raw`\bar`, syntax: '{x}', info: 'Bar accent x̄', sample: String.raw`\bar{x}` },
      { label: String.raw`\vec`, syntax: '{x}', info: 'Vector arrow x⃗', sample: String.raw`\vec{v}` },
      { label: String.raw`\dot`, syntax: '{x}', info: 'Dot accent ẋ', sample: String.raw`\dot{x}` },
      { label: String.raw`\ddot`, syntax: '{x}', info: 'Double dot ẍ', sample: String.raw`\ddot{x}` },
      { label: String.raw`\tilde`, syntax: '{x}', info: 'Tilde accent x̃', sample: String.raw`\tilde{x}` },
      { label: String.raw`\widehat`, syntax: '{x}', info: 'Wide hat', sample: String.raw`\widehat{ABC}` },
      { label: String.raw`\widetilde`, syntax: '{x}', info: 'Wide tilde', sample: String.raw`\widetilde{ABC}` },
      { label: String.raw`\overline`, syntax: '{expr}', info: 'Overline above expression', sample: String.raw`\overline{AB}` },
      { label: String.raw`\underline`, syntax: '{expr}', info: 'Underline below expression', sample: String.raw`\underline{AB}` },
      { label: String.raw`\overbrace`, syntax: '{expr}^{label}', info: 'Brace above', sample: String.raw`\overbrace{a+b}^{n}` },
      { label: String.raw`\underbrace`, syntax: '{expr}_{label}', info: 'Brace below', sample: String.raw`\underbrace{a+b}_{n}` },
      { label: String.raw`\boxed`, syntax: '{expr}', info: 'Boxed formula', sample: String.raw`\boxed{E=mc^2}` },
      { label: String.raw`\cancel`, syntax: '{expr}', info: 'Strikethrough', sample: String.raw`\cancel{x}` },
    ],
  },
  {
    title: 'Delimiters',
    accent: '#b45309',
    entries: [
      { label: String.raw`\left`, syntax: String.raw`( \cdots \right)`, info: 'Auto-sized left delimiter', sample: String.raw`\left( \frac{a}{b} \right)` },
      { label: String.raw`\lvert`, syntax: '', info: 'Left vertical bar |', sample: String.raw`\lvert x \rvert` },
      { label: String.raw`\lVert`, syntax: '', info: 'Left double bar ‖', sample: String.raw`\lVert x \rVert` },
      { label: String.raw`\lfloor`, syntax: '', info: 'Left floor ⌊', sample: String.raw`\lfloor x \rfloor` },
      { label: String.raw`\lceil`, syntax: '', info: 'Left ceiling ⌈', sample: String.raw`\lceil x \rceil` },
      { label: String.raw`\langle`, syntax: '', info: 'Left angle ⟨', sample: String.raw`\langle x \rangle` },
    ],
  },
  {
    title: 'Logic & Sets',
    accent: '#1d4ed8',
    entries: [
      { label: String.raw`\forall`, syntax: '', info: 'For all ∀', sample: String.raw`\forall x` },
      { label: String.raw`\exists`, syntax: '', info: 'There exists ∃', sample: String.raw`\exists x` },
      { label: String.raw`\nexists`, syntax: '', info: 'Does not exist ∄', sample: String.raw`\nexists x` },
      { label: String.raw`\neg`, syntax: '', info: 'Negation ¬', sample: String.raw`\neg P` },
      { label: String.raw`\land`, syntax: '', info: 'Logical and ∧', sample: String.raw`P \land Q` },
      { label: String.raw`\lor`, syntax: '', info: 'Logical or ∨', sample: String.raw`P \lor Q` },
      { label: String.raw`\cup`, syntax: '', info: 'Union ∪', sample: String.raw`A \cup B` },
      { label: String.raw`\cap`, syntax: '', info: 'Intersection ∩', sample: String.raw`A \cap B` },
      { label: String.raw`\setminus`, syntax: '', info: 'Set difference ∖', sample: String.raw`A \setminus B` },
      { label: String.raw`\emptyset`, syntax: '', info: 'Empty set ∅', sample: String.raw`\emptyset` },
      { label: String.raw`\varnothing`, syntax: '', info: 'Empty set (variant) ∅', sample: String.raw`\varnothing` },
    ],
  },
  {
    title: 'Symbols',
    accent: '#dc2626',
    entries: [
      { label: String.raw`\cdot`, syntax: '', info: 'Centered dot ·', sample: String.raw`a \cdot b` },
      { label: String.raw`\cdots`, syntax: '', info: 'Centered ellipsis ⋯', sample: String.raw`a + \cdots + z` },
      { label: String.raw`\ldots`, syntax: '', info: 'Low ellipsis …', sample: String.raw`a, \ldots, z` },
      { label: String.raw`\vdots`, syntax: '', info: 'Vertical dots ⋮', sample: String.raw`\vdots` },
      { label: String.raw`\ddots`, syntax: '', info: 'Diagonal dots ⋱', sample: String.raw`\ddots` },
      { label: String.raw`\infty`, syntax: '', info: 'Infinity ∞', sample: String.raw`\infty` },
      { label: String.raw`\partial`, syntax: '', info: 'Partial derivative ∂', sample: String.raw`\partial f` },
      { label: String.raw`\nabla`, syntax: '', info: 'Nabla / del ∇', sample: String.raw`\nabla f` },
      { label: String.raw`\pm`, syntax: '', info: 'Plus-minus ±', sample: String.raw`a \pm b` },
      { label: String.raw`\mp`, syntax: '', info: 'Minus-plus ∓', sample: String.raw`a \mp b` },
      { label: String.raw`\times`, syntax: '', info: 'Multiplication ×', sample: String.raw`a \times b` },
      { label: String.raw`\div`, syntax: '', info: 'Division ÷', sample: String.raw`a \div b` },
      { label: String.raw`\circ`, syntax: '', info: 'Composition ∘', sample: String.raw`f \circ g` },
      { label: String.raw`\oplus`, syntax: '', info: 'Circled plus ⊕', sample: String.raw`a \oplus b` },
      { label: String.raw`\otimes`, syntax: '', info: 'Tensor product ⊗', sample: String.raw`a \otimes b` },
      { label: String.raw`\hbar`, syntax: '', info: 'Reduced Planck constant ℏ', sample: String.raw`\hbar` },
      { label: String.raw`\ell`, syntax: '', info: 'Script l ℓ', sample: String.raw`\ell` },
      { label: String.raw`\Re`, syntax: '', info: 'Real part ℜ', sample: String.raw`\Re(z)` },
      { label: String.raw`\Im`, syntax: '', info: 'Imaginary part ℑ', sample: String.raw`\Im(z)` },
      { label: String.raw`\angle`, syntax: '', info: 'Angle ∠', sample: String.raw`\angle ABC` },
    ],
  },
];
